BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using System.Security.Claims;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize]
public class OrderController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;
    
    [BindProperty]
    public OrderVM OrderVm { get; set; }
    
    public OrderController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
    }
    // GET
    public IActionResult Index()
    {
        return View();
    }
    
    public IActionResult Details(int orderId)
    {
        OrderVm = new()
        {
            OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
            OrderDetails = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderId == orderId, includeProperties:"Product")
        };
        return View(OrderVm);
    }
    
    [Authorize(Roles = SD.RoleAdmin + "," + SD.RoleEmployee)]
    [HttpPost]
    public IActionResult UpdateOrderDetail()
    {
        var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVm.OrderHeader.Id);
        orderHeaderFromDb.Name = OrderVm.OrderHeader.Name;
        orderHeaderFromDb.PhoneNumber = OrderVm.OrderHeader.PhoneNumber;
        orderHeaderFromDb.StreetAddress = OrderVm.OrderHeader.StreetAddress;
        orderHeaderFromDb.City = OrderVm.OrderHeader.City;
        orderHeaderFromDb.State = OrderVm.OrderHeader.State;
        orderHeaderFromDb.PostalCode = OrderVm.OrderHeader.PostalCode;
        if (!string.IsNullOrEmpty(OrderVm.OrderHeader.Carrier))
        {
            orderHeaderFromDb.Carrier = OrderVm.OrderHeader.Carrier;
        }
        if (!string.IsNullOrEmpty(OrderVm.OrderHeader.TrackingNumber))
        {
            orderHeaderFromDb.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
        }
        _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
        _unitOfWork.Save();

        TempData["success"] = "Order Details updated Successfully.";
        return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDb.Id });
    }
    
    [Authorize(Roles = SD.RoleAdmin + "," + SD.RoleEmployee)]
    [HttpPost]
    public IActionResult StartProcessing()
    {
    
        
        _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, SD.StatusInProcess);
        _unitOfWork.Save();
        
        TempData["success"] = "Order Status updated Successfully.";
        return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
    }
    
    [Authorize(Roles = SD.RoleAdmin + "," + SD.RoleEmployee)]
    [HttpPost]
    public IActionResult ShipOrder()
    {
        var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVm.OrderHeader.Id);
        orderHeaderFromDb.TrackingNumber = OrderVm.OrderHeader.TrackingNumber;
        orderHeaderFromDb.Carrier = OrderVm.OrderHeader.Carrier;
        orderHeaderFromDb.OrderStatus = SD.StatusShipped;
        orderHeaderFromDb.ShippingDate = DateTime.UtcNow;
        if (orderHeaderFromDb.PaymentStatus == SD.PaymentStatusDelayedPayment)
        {
            orderHeaderFromDb.PaymentDueDate = DateOnly.FromDateTime(DateTime.UtcNow.AddDays(30));
        }
        
        _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
        _unitOfWork.Save();
        
        TempData["success"] = "Order Shipped Successfully.";
        return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
    }
    
    [Authorize(Roles = SD.RoleAdmin + "," + SD.RoleEmployee)]
    [HttpPost]
    public IActionResult CancelOrder()
    {
        var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVm.OrderHeader.Id);
        if (orderHeaderFromDb.PaymentStatus == SD.PaymentStatusApproved)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderHeaderFromDb.Id, SD.StatusCancelled, SD.StatusRefunded);
        }
        else
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderHeaderFromDb.Id, SD.StatusCancelled, SD.StatusCancelled);
        }
        
        _unitOfWork.Save();
        
        TempData["success"] = "Order Cancelled Successfully.";
        return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
    }
    
    [Authorize(Roles = SD.RoleAdmin + "," + SD.RoleEmployee)]
    [HttpPost]
    public IActionResult PayNow()
    {
        if (OrderVm.OrderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVm.OrderHeader.Id, OrderVm.OrderHeader.OrderStatus, SD.StatusApproved);
            _unitOfWork.Save();
        }
        
        TempData["success"] = "Order Paid Successfully.";
        return RedirectToAction(nameof(Details), new { orderId = OrderVm.OrderHeader.Id });
    }
    
    #region API_CALLS

    [HttpGet]
    public IActionResult GetAll(string? status)
    {
        var objOrderHeadersList = _unitOfWork.OrderHeader.GetAll(includeProperties:"ApplicationUser");
        if (!(User.IsInRole(SD.RoleAdmin) || User.IsInRole(SD.RoleEmployee)))
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            objOrderHeadersList = objOrderHeadersList.Where(u => u.ApplicationUserId == userId);
        }
        switch (status)
        {
            case "pending":
                objOrderHeadersList =
                    objOrderHeadersList.Where(u => u.PaymentStatus.Equals(SD.PaymentStatusDelayedPayment));
                break;
            case "inprocess":
                objOrderHeadersList =
                    objOrderHeadersList.Where(u => u.OrderStatus.Equals(SD.StatusInProcess));
                break;
            case "completed":
                objOrderHeadersList =
                    objOrderHeadersList.Where(u => u.OrderStatus.Equals(SD.StatusCompleted));
                break;
            case "approved":
                objOrderHeadersList =
                    objOrderHeadersList.Where(u => u.OrderStatus.Equals(SD.StatusApproved));
                break;
        }
        return Json(new { data = objOrderHeadersList });
    }
    

    #endregion
}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BulkyWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.RoleAdmin)]
public class UserController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly ILogger<UserController> _logger;
    
    public UserController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, ILogger<UserController> logger, RoleManager<IdentityRole> roleManager)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _logger = logger;
        _roleManager = roleManager;
    }
    
    // GET
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult RoleManagement(string id)
    {
        var user = _unitOfWork.ApplicationUser.Get(u => u.Id == id, includeProperties:"Company");
        UserRoleVM roleVm = new()
        {
            User = user,
            Roles = _roleManager.Roles.Select(i=> new SelectListItem()
            {
                Text = i.Name,
                Value = i.Name
            }),
            Companies = _unitOfWork.Company.GetAll().Select(i=>new SelectListItem()
            {
                Text = i.Name,
                Value = i.Id.ToString()
            })
        };

        roleVm.User.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
        return View(roleVm);
    }
    
    [HttpPost]
    public IActionResult UpdateRole(UserRoleVM roleVm)
    {
        _logger.Log(LogLevel.Information,"Reached");
        var user = _unitOfWork.ApplicationUser.Get(u => u.Id == roleVm.User.Id);
        var oldRole = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

        if (!(roleVm.User.Role == oldRole))
        {
            if (roleVm.User.Role == SD.RoleCompany)
            {
                user.CompanyId = roleVm.User.CompanyId;
            }

            if (oldRole == SD.RoleCompany)
            {
                user.CompanyId = null;
            }
            _unitOfWork.ApplicationUser.Update(user);
            _unitOfWork.Save();
            _userManager.RemoveFromRoleAsync(user, oldRole).GetAwaiter().GetResult();
            _userManager.AddToRoleAsync(user, roleVm.User.Role).GetAwaiter().GetResult();
        }
        else
        {
            if (oldRole == SD.RoleCompany && user.CompanyId != roleVm.User.CompanyId)
            {
                user.CompanyId = roleVm.User.CompanyId;
                _unitOfWork.ApplicationUser.Update(user);
                _unitOfWork.Save();
            }
        }
        
        return RedirectToAction(nameof(Index));
    }

    #region API_CALLS
    

    [HttpGet]
    public IActionResult GetAll()
    {
        var objUsersList = _unitOfWork.ApplicationUser.GetAll(includeProperties:"Company").ToList();
        foreach (var user in objUsersList)
        {
            user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            
            if (user.Company == null)
            {
                user.Company = new() { Name = "" };
            }
        }
        return Json(new { data = objUsersList });
    }
    
    
    
    [HttpPost]
    public IActionResult LockUnlock([FromBody] string id)
    {
        var objFromDb = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
        if (objFromDb == null)
        {
            return Json(new { sucess = false, message = $"Error while locking/unlocking for user with id {id}." });
        }

        if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.UtcNow)
        {
            objFromDb.LockoutEnd = DateTime.UtcNow;
        }
        else
        {
            objFromDb.LockoutEnd = DateTime.UtcNow.AddYears(1000);
        }
        _unitOfWork.ApplicationUser.Update(objFromDb);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Operation successful" });
    }
    

    #endregion
}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using System.Security.Claims;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Utility;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.ViewComponents;

public class ShoppingCartViewComponent : ViewComponent
{
    private readonly IUnitOfWork _unitOfWork;
    public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        if (claim != null)
        {
            if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                HttpContext.Session.SetInt32(SD.SessionCart,
                    _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
            
            return View(HttpContext.Session.GetInt32(SD.SessionCart));
        }
        
        HttpContext.Session.Clear();
        return View(0);
        
    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BulkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/Images/book.png" style="width: 30px"/>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.Identity is { IsAuthenticated: true })
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                    }
                    
                    @if (User.IsInRole(SD.RoleAdmin))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                </li>
                                
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                    }
                   
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index">&nbsp; 
                            @await Component.InvokeAsync("ShoppingCart")
                        </a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer bg-primary text-muted">
    <div class="container text-center">
      Made with  <i class="bi bi-heart-fill"></i> by Malik
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<partial name="_ToastrScript"/>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.tiny.cloud/1/m5leolrkmlsblvrzyhztl6mx9u6gknor8ha1u1w0sceyma9h/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
<script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <partial name="_ToastrScript"/>
    <script type="text/javascript">
        toastr.success(`@TempData["success"]`);
    </script>
    
}

@if (TempData["error"] != null)
{
    <partial name="_ToastrScript"/>
    <script type="text/javascript">
        toastr.success(`@TempData["error"]`);
    </script>
}

BulkyWeb/Views/Shared/_ToastrScript.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>